name: Build, Publish to PyPI, and Create GitHub Release (Windows)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Download and extract PortAudio binaries
        run: |
          curl -L -o portaudio.zip https://github.com/PortAudio/portaudio/archive/refs/tags/v19.7.0.zip
          7z x portaudio.zip -oportaudio
        shell: bash

      - name: Build distributions
        run: |
          set "INCLUDE=%cd%\portaudio\include;%INCLUDE%"
          set "LIB=%cd%\portaudio\lib;%LIB%"
          cd pyaudio
          python -m pip install --upgrade pip build
          python -m build
        shell: cmd

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: pyaudio/dist/

  github-release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/

      - name: Get version from dist filename
        id: get_version
        run: |
          $file = Get-ChildItem -Path dist\*.tar.gz | Select-Object -First 1
          if ($file) {
            if ($file.Name -match "^[^-]+-([0-9]+\.[0-9]+\.[0-9]+)\.tar\.gz$") {
              echo "VERSION=$($matches[1])" >> $env:GITHUB_OUTPUT
            }
          }

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.get_version.outputs.VERSION }}
          name: Release v${{ steps.get_version.outputs.VERSION }}
          generate_release_notes: true
          files: |
            dist\*
